# Generated by Django 4.2.7 on 2023-12-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfirm',
            old_name='users',
            new_name='user',
        ),
    ]
